import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRules } from '../src/rules.mjs';
import { newEngine } from '../src/scan.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
// Private-key fixtures are assembled at runtime with the BEGIN marker kept in a
// separate fragment so this test source does not itself trip the secret rule.
const BEGIN = '-----BEGIN ';

const contracts = {
    'attribution.claude-coauthor': {
        positive: { text: 'Co-authored-by: Claude Code <noreply@anthropic.com>' },
        nearMiss: { text: 'Co-authored-by: Claude Dupont <claude@example.com>' },
    },
    'attribution.copilot-coauthor': {
        positive: { text: 'Co-authored-by: GitHub Copilot <175728472+Copilot@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Copilot Team <copilot-team@example.com>' },
    },
    'attribution.codex-coauthor': {
        positive: { text: 'Co-authored-by: OpenAI Codex <noreply@openai.com>' },
        nearMiss: { text: 'Co-authored-by: Cody Dexter <cody@openai.com>' },
    },
    'attribution.bot-coauthor': {
        positive: { text: 'Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Robin Ott <robin@example.com>' },
    },
    'attribution.generated-with': {
        positive: { text: 'Generated with Claude Code' },
        nearMiss: { text: 'Do not show the Generated with Claude Code badge in settings.' },
    },
    'attribution.ai-noreply': {
        positive: { text: 'Reviewed-by: Assistant <noreply@openai.com>' },
        nearMiss: { text: 'Report abuse to noreply@openai.com if you see it.' },
    },
    'marker.corner-cut': {
        positive: { path: 'src/parser.js', text: '// ponytail: skip malformed records for now' },
        nearMiss: { path: 'docs/parser.js', text: '// ponytail: example of a prohibited marker' },
    },
    'marker.ai-authored': {
        positive: { path: 'src/parser.js', text: '// generated by AI' },
        nearMiss: { path: 'tests/parser.js', text: '// generated by AI' },
    },
    'claude.local-settings': {
        positive: { path: 'packages/web/.claude/settings.local.json' },
        nearMiss: { path: 'packages/web/.claude/settings.json' },
    },
    'claude.session-state': {
        positive: { path: '.claude/session-2026-07-13.json' },
        nearMiss: { path: '.claude/commands/release.md' },
    },
    'codex.session-state': {
        positive: { path: '.codex/sessions/2026/rollout.jsonl' },
        nearMiss: { path: '.codex/config.toml' },
    },
    'copilot.session-state': {
        positive: { path: 'packages/web/.copilot/config.json' },
        nearMiss: { path: 'packages/web/copilot/config.json' },
    },
    'cursor.session-state': {
        positive: { path: '.cursor/chats/feature.json' },
        nearMiss: { path: '.cursor/rules/project.mdc' },
    },
    'aider.history': {
        positive: { path: 'packages/web/.aider.conf.yml' },
        nearMiss: { path: 'packages/web/aider.conf.yml' },
    },
    'specstory.history': {
        positive: { path: '.specstory/history/session.json' },
        nearMiss: { path: 'docs/specstory/history.md' },
    },
    'continue.sessions': {
        positive: { path: '.continue/sessions/active.json' },
        nearMiss: { path: '.continue/config.yaml' },
    },
    'secret.dotenv': {
        positive: { path: 'services/api/.env.production' },
        nearMiss: { path: 'services/api/.env.example' },
    },
    'secret.private-key': {
        positive: { path: 'certificates/id_ed25519' },
        nearMiss: { path: 'certificates/server.pem' },
    },
    'secret.aws-credentials': {
        positive: { path: 'deploy/.aws/credentials' },
        nearMiss: { path: 'deploy/.aws/config' },
    },
    'secret.claude-credentials': {
        positive: { path: '.claude/.credentials.json' },
        nearMiss: { path: '.claude/credentials.example.json' },
    },
    'generic.agent-instructions': {
        positive: { path: 'packages/api/AGENTS.md' },
        nearMiss: { path: 'docs/agent-guide.md' },
    },
    'generic.project-policy': {
        positive: { path: '.aimhooman.json' },
        nearMiss: { path: '.aimhooman.example.json' },
    },
    'playwright-mcp.state': {
        positive: { path: '.playwright-mcp/traces/run.json' },
        nearMiss: { path: 'playwright.config.mjs' },
    },
    'remember.state': {
        positive: { path: 'packages/app/.remember/notes.json' },
        nearMiss: { path: 'docs/REMEMBER.md' },
    },
    'superpowers.state': {
        positive: { path: '.superpowers/cache/state.json' },
        nearMiss: { path: '.superpowers.md' },
    },
    'agent.state': {
        positive: { path: '.agent/state.json' },
        nearMiss: { path: '.agents/rules/aimhooman.md' },
    },
    'secret.private-key-content': {
        positive: { path: 'config/credential.txt', text: `${BEGIN}OPENSSH PRIVATE KEY-----` },
        nearMiss: { path: 'certificates/server.pem', text: '-----BEGIN CERTIFICATE-----' },
    },
    'secret.service-account-key': {
        positive: { path: 'config/service-account.json', text: `  "private_key": "${BEGIN}PRIVATE KEY-----\\nMII..."` },
        nearMiss: { path: 'config/service-account.example.json', text: '  "private_key": "${SERVICE_ACCOUNT_PRIVATE_KEY}"' },
    },
    'secret.aws-key-content': {
        positive: { path: 'config/aws.ini', text: `aws_secret_access_key = ${'a'.repeat(40)}` },
        nearMiss: { path: 'config/aws.example.ini', text: 'aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}' },
    },
    'secret.provider-token': {
        positive: { path: 'config/token.txt', text: `ghp_${'a'.repeat(36)}` },
        nearMiss: { path: 'config/token.example.txt', text: 'ghp_REPLACE_ME' },
    },
};

function findingsFor(engine, rule, input) {
    if (rule.kind === 'path') return engine.checkPaths([input.path]);
    if (rule.kind === 'message') return engine.checkMessage(input.text);
    return engine.checkContent(input.path, input.text);
}

function matchFor(findings, ruleId) {
    return findings
        .flatMap((finding) => finding.matchedRules)
        .find((match) => match.ruleId === ruleId);
}

test('every built-in rule has a positive and a meaningful near-miss contract', () => {
    const rules = loadRules();
    const ruleIds = rules.map((rule) => rule.id).sort();
    assert.deepEqual(
        Object.keys(contracts).sort(),
        ruleIds,
        'update the contract registry whenever the built-in rule catalog changes'
    );

    const engine = newEngine('clean');
    for (const rule of rules) {
        const contract = contracts[rule.id];
        assert.ok(contract.positive, `${rule.id} needs a positive contract`);
        assert.ok(contract.nearMiss, `${rule.id} needs a near-miss contract`);

        const positive = matchFor(findingsFor(engine, rule, contract.positive), rule.id);
        assert.ok(positive, `${rule.id} did not match its positive contract`);
        assert.equal(positive.decision, rule.actions.clean, `${rule.id} clean decision changed`);

        const nearMiss = matchFor(findingsFor(engine, rule, contract.nearMiss), rule.id);
        assert.equal(nearMiss, undefined, `${rule.id} matched its near-miss contract`);
    }
});

test('aws access key IDs are blocked, but AWS\'s published example keys are not', () => {
    const engine = newEngine('clean');
    const matched = (text) => Boolean(
        matchFor(engine.checkContent('infra/main.tf', text), 'secret.aws-key-content')
    );

    // Split so this file never carries a literal that trips the rule it tests.
    const body = 'Q7QQVQ3ZK4WQ2XYZ';

    // A real access key ID carries no naming context, which the aws_secret_access_key
    // pattern needs, so the prefix has to stand on its own.
    assert.ok(matched(`provider "aws" { access_key = "AKIA${body}" }`));
    assert.ok(matched(`AWS_SESSION_ID=ASIA${body}`), 'STS keys use the ASIA prefix');

    // AWS publishes these in its own docs, and they land in READMEs, Terraform
    // samples, and test fixtures. Blocking them stops legitimate commits.
    assert.equal(matched('access_key = "AKIAIOSFODNN7EXAMPLE"'), false);
    assert.equal(matched('access_key = "ASIAIOSFODNN7EXAMPLE"'), false);
    assert.equal(matched('access_key = "AKIAI44QH8DHBEXAMPLE"'), false);

    // Word boundaries keep the prefix from matching a shorter or longer run.
    assert.equal(matched('const region = "AKIA123";'), false);
    assert.equal(matched(`token=XAKIA${body}`), false);
    assert.equal(matched(`token=AKIA${body}9`), false);
});

// F-15e1: the AWS example secret access key (`wJalrXUtnFEMI/...EXAMPLEKEY`)
// is printed next to `AKIAIOSFODNN7EXAMPLE` on every AWS docs page. The 0.1.5
// exception only covered the access key ID; the secret access key stayed
// blocked. The v3 pattern adds a lookbehind so a value ending in EXAMPLEKEY
// (the documented example shape) is not flagged, while a real key that merely
// contains EXAMPLEKEY as a substring stays blocked.
test('AWS example secret access key is allowed, real keys are still blocked', () => {
    const engine = newEngine('clean');
    const matched = (text) => Boolean(
        matchFor(engine.checkContent('config/aws.ini', text), 'secret.aws-key-content')
    );

    // AWS's documented example pair — the secret access key half. This was the
    // original 0.1.5 miss: the access key ID (`AKIAIOSFODNN7EXAMPLE`) was
    // excepted, but its printed pair was not.
    const exampleSecret = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY';
    assert.equal(matched(`aws_secret_access_key = ${exampleSecret}`), false, 'AWS doc example secret must not block');
    assert.equal(matched(`aws_secret_access_key = "${exampleSecret}"`), false, 'quoted AWS doc example secret must not block');
    assert.equal(matched(`AWS_SESSION_TOKEN=${exampleSecret}`), false, 'AWS doc example session token must not block');

    // Real-shape keys (no EXAMPLEKEY suffix) still block. Use a literal split so
    // this file does not carry a single 40-char run that looks like a live key.
    const realHead = 'wJalrXUtnFEMI7K7MDENG';
    const realTail = 'bPxRfiCYzXmpir3Qw';
    assert.ok(matched(`aws_secret_access_key = ${realHead}${realTail}`), 'real 40-char secret must block');
    assert.ok(matched(`aws_secret_access_key = "${realHead}${realTail}"`), 'real quoted secret must block');

    // A key that merely contains EXAMPLEKEY as a substring (not as a suffix) is
    // a real key and must still block. The fix narrows the exception to the
    // documented example shape (ends in EXAMPLEKEY), not to any value containing it.
    assert.ok(
        matched(`aws_secret_access_key = aEXAMPLEKEY${'a'.repeat(30)}`),
        'real key with EXAMPLEKEY substring must still block',
    );
});

test('source markers stay out of documentation, tests, dependencies, and generated output', () => {
    const engine = newEngine('strict');
    const excludedPaths = [
        'docs/example.js',
        'test/example.js',
        'tests/example.js',
        'src/__tests__/example.js',
        'pkg/testdata/golden.js',
        'fixtures/example.js',
        '__fixtures__/example.js',
        'vendor/example.js',
        'vendored/example.js',
        'third_party/example.js',
        'node_modules/example/index.js',
        'dist/example.js',
        'build/example.js',
        'out/example.js',
        'target/example.js',
        '.next/static/example.js',
        'coverage/example.js',
        'generated/example.js',
        'src/example.generated.js',
        'src/example.min.js',
        'src/example.map',
        'src/example.md',
        'src/example.mdx',
        'src/example.markdown',
        'src/example.rst',
        'src/example.test.js',
        'src/example.spec.ts',
        'pkg/example_test.go',
        'spec/models/user_spec.rb',
    ];
    const markerIds = new Set(['marker.corner-cut', 'marker.ai-authored']);
    for (const path of excludedPaths) {
        const findings = engine.checkContent(path, '// ponytail: shortcut\n// generated by AI');
        const ids = findings.flatMap((finding) => finding.matchedRuleIds);
        assert.equal(ids.some((id) => markerIds.has(id)), false, path);
    }

    assert.ok(matchFor(engine.checkContent('src/example.js', '// ponytail: shortcut'), 'marker.corner-cut'));
    assert.ok(matchFor(engine.checkContent('src/example.js', '// generated by AI'), 'marker.ai-authored'));
    // Build output is excepted at the repository root only. `out` and `spec` are
    // ordinary module names, and a marker in one is owned source.
    assert.ok(matchFor(engine.checkContent('src/out/json.js', '// ponytail: shortcut'), 'marker.corner-cut'));
    assert.ok(matchFor(engine.checkContent('src/spec/openapi-builder.js', '// ponytail: shortcut'), 'marker.corner-cut'));
});

test('marker.ai-authored matches the marker phrase, not a product that ships an AI feature', () => {
    // "AI-generated" is vocabulary, not a marker: it is a UI label, a column
    // name, a union member and a disclaimer in any product with an AI feature.
    const engine = newEngine('strict');
    const ownedSource = [
        ['src/ui/Badge.tsx', '<Badge>AI-generated</Badge>'],
        ['src/db/schema.ts', '  aiGenerated: boolean("ai_generated").notNull(),'],
        ['src/api/types.ts', 'type Source = "human" | "ai-generated";'],
        ['src/copy/strings.ts', '"disclaimer": "AI-generated content may be inaccurate"'],
    ];
    for (const [path, line] of ownedSource) {
        assert.equal(matchFor(engine.checkContent(path, line), 'marker.ai-authored'), undefined, line);
    }
    for (const vendor of ['AI', 'Copilot', 'Claude', 'ChatGPT', 'Codex']) {
        assert.ok(
            matchFor(engine.checkContent('src/parser.js', `// generated by ${vendor}`), 'marker.ai-authored'),
            vendor,
        );
    }
});

test('corner-cut labels match case-insensitively without broadening near misses', () => {
    for (const profile of ['clean', 'strict', 'compliance']) {
        const engine = newEngine(profile);
        const expected = profile === 'strict' ? 'block' : 'review';
        for (const label of ['ponytail', 'Ponytail', 'PONYTAIL', 'Caveman', 'YAGNI-ONELINER']) {
            const match = matchFor(
                engine.checkContent('src/example.js', `// ${label}: shortcut`),
                'marker.corner-cut',
            );
            assert.equal(match?.decision, expected, `${profile}: ${label}`);
        }
        assert.equal(
            matchFor(engine.checkContent('src/example.js', '// ponytail : is prose'), 'marker.corner-cut'),
            undefined,
        );
    }
});

test('secret, session and policy paths match case-insensitively; instruction paths do not', () => {
    const engine = newEngine('strict');
    // On APFS and NTFS these are the same file as their lowercase spellings, and
    // Git records the case the caller typed rather than the case on disk.
    const cases = [
        ['.ENV', 'secret.dotenv'],
        ['nested/.EnV.Production', 'secret.dotenv'],
        ['deploy/.AWS/CREDENTIALS', 'secret.aws-credentials'],
        ['keys/ID_ED25519', 'secret.private-key'],
        ['.CLAUDE/session.json', 'claude.session-state'],
        ['.Claude/settings.local.json', 'claude.local-settings'],
        ['.Codex/sessions/rollout.jsonl', 'codex.session-state'],
        ['.Cursor/chats/feature.json', 'cursor.session-state'],
        ['.Aimhooman.json', 'generic.project-policy'],
    ];
    for (const [path, ruleId] of cases) {
        assert.ok(matchFor(engine.checkPaths([path]), ruleId), path);
    }
    assert.equal(engine.checkPaths(['.ENV.EXAMPLE']).length, 0);

    // The negative control for the opt-in: generic.agent-instructions stays
    // case-sensitive, so folding case is still a per-rule decision rather than a
    // global one. Its names lowercase to ordinary documentation filenames, which
    // must keep committing freely.
    for (const path of ['docs/claude.md', 'docs/gemini.md', 'website/content/blog/agents.md']) {
        assert.equal(engine.checkPaths([path]).length, 0, path);
    }
});

test('the review-required rules print the bound review command as their fix', () => {
    // A bare `allow` writes no head and no object binding, so it exempts every
    // future content of the path. Only `review` binds to the reviewed object, so
    // it is the only remediation these two can honestly print.
    const reviewRequired = new Set(['generic.agent-instructions', 'generic.project-policy']);
    const rules = loadRules().filter((rule) => reviewRequired.has(rule.id));
    assert.equal(rules.length, reviewRequired.size, 'the review-required rule set moved');
    for (const rule of rules) {
        const fix = rule.remediation.join('\n');
        assert.match(fix, /aimhooman review .* --head <commit>/, `${rule.id} must name the bound command`);
        assert.equal(/aimhooman allow\b/.test(fix), false, `${rule.id} prints an unbound allow as its fix`);
    }
});

// UT-03b: a content secret finding used to stop at "remove it, rotate it" and
// never mentioned the one sanctioned way to keep an intentional fixture (docs
// quoting a key header, a detection test fixture). The path secret rules set
// that standard already; the content rules now print the bound secret-path
// allow too. A bare allow cannot silence a secret, so this is the only command
// they may honestly name.
test('content secret rules name the deliberate-fixture escape hatch in their remediation', () => {
    const secrets = loadRules().filter((rule) => rule.category === 'secret' && rule.kind === 'code');
    assert.ok(secrets.length >= 4, 'the content secret rule set moved');
    for (const rule of secrets) {
        assert.ok(
            rule.remediation.some((line) => line.includes('aimhooman allow <path> --scope secret-path')),
            `${rule.id} does not name the secret-path allow in its remediation`,
        );
    }
});

test('message attribution repair is exact and compliance preserves disclosures', () => {
    const clean = newEngine('clean');
    const compliance = newEngine('compliance');
    const exactLines = [
        'Co-authored-by: Claude <noreply@anthropic.com>',
        'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
        'Co-authored-by: Codex <noreply@openai.com>',
        'Generated by ChatGPT',
        '🤖 Generated with [Claude Code](https://claude.ai/code)',
    ];
    for (const line of exactLines) {
        const input = `Subject\n\n${line}\nDetail\n`;
        const fixed = clean.fixMessage(input);
        assert.equal(fixed.removed.length, 1, line);
        assert.equal(fixed.cleaned, 'Subject\n\nDetail\n', line);
        assert.equal(compliance.checkMessage(input).length, 0, line);
        assert.equal(compliance.fixMessage(input).cleaned, input, line);
    }

    const nearMisses = [
        'Co-authored-by: Claude Dupont <claude@example.com>',
        'Do not show the Generated by ChatGPT badge in settings.',
        'Report abuse to noreply@openai.com if you see it.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
        assert.deepEqual(clean.fixMessage(line), { cleaned: line, removed: [] }, line);
    }
});

test('attribution rules block the footer Claude Code emits today', () => {
    const clean = newEngine('clean');
    const message = [
        'feat: add thing',
        '',
        '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
        '',
        'Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>',
        '',
    ].join('\n');

    const fixed = clean.fixMessage(message);
    assert.equal(fixed.removed.length, 2, 'both footer lines must be repaired');
    assert.equal(fixed.cleaned.includes('Generated with'), false);
    assert.equal(fixed.cleaned.includes('noreply@anthropic.com'), false);
    assert.ok(fixed.cleaned.startsWith('feat: add thing'), 'the subject must survive');
});

test('attribution patterns pin neither a vendor URL nor a product display name', () => {
    // Vendor links are marketing surface and get rebranded (claude.ai/code ->
    // claude.com/claude-code); a pinned one rots silently while CI stays green.
    // Match the link's shape and anchor on the noreply mail domain, which is
    // infrastructure and does not move. Product names rot the same way — the
    // footer already grew from "Claude Code" to "Claude Sonnet 4.5" — so pin the
    // vendor and let the suffix follow it.
    for (const rule of loadRules().filter((rule) => rule.category === 'ai-attribution')) {
        for (const pattern of rule.match.content ?? []) {
            assert.equal(
                /https?:/i.test(pattern),
                false,
                `${rule.id} pins a vendor URL: ${pattern}`
            );
            assert.equal(
                /\b(?:code|sonnet|opus|haiku)\b/i.test(pattern),
                false,
                `${rule.id} pins a product display name: ${pattern}`
            );
        }
    }
});

test('the generated-with rule survives a model suffix, a version and an emoji', () => {
    const clean = newEngine('clean');
    const footers = [
        'Generated with Claude Code',
        '🤖 Generated with Claude Code',
        'Generated with Claude Code 🤖',
        'Generated with Claude Sonnet 4.5',
        'Generated with Claude Opus 4.8',
        'Generated with Claude Code v2.0.1',
        '🤖 Generated with [Claude Sonnet 4.5](https://claude.com/claude-code)',
        // The gpt-N forms live only inside the alternation; nothing else covers
        // them, so dropping them would otherwise go unnoticed.
        'Generated by GPT-4',
        'Generated by GPT-4.5',
        'Generated by GPT-5',
        'Generated by ChatGPT',
        'Generated with GitHub Copilot',
        'Generated with OpenAI Codex',
        'Generated with Cursor',
    ];
    for (const line of footers) {
        const match = matchFor(clean.checkMessage(line), 'attribution.generated-with');
        assert.equal(match?.decision, 'block', line);
    }
});

test('attribution patterns stay cheap on adversarial input', () => {
    // A trailer whose "<" never arrives. Built-in patterns are exempt from the
    // local input cap (src/rules.mjs), so an unbounded commit message line
    // reaches them directly; an ambiguous quantifier pair here cost 49s at this
    // length. The budget is loose on purpose: it catches catastrophic
    // backtracking, not slow machines.
    const engine = newEngine('clean');
    const line = `x-by:${' '.repeat(6400)}`;
    const start = process.hrtime.bigint();
    engine.checkMessage(line);
    const ms = Number(process.hrtime.bigint() - start) / 1e6;
    assert.ok(ms < 1000, `attribution scan took ${ms.toFixed(0)}ms on adversarial input`);
});

test('generalized attribution patterns do not swallow ordinary trailers or prose', () => {
    const clean = newEngine('clean');
    const nearMisses = [
        'Generated with [our release script](https://ci.example.com/docs)',
        'Co-authored-by: Claude Dupont <claude.dupont@example.com>',
        'Co-authored-by: Codexter Ltd <team@example.com>',
        'Reviewed-by: Robin Ott <robin@example.com>',
        'See https://claude.com/claude-code for the changelog.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
    }
});

test('env placeholders are excepted by suffix while real env files still block', () => {
    // The rule tells the user to commit a placeholder instead, so every ordering
    // of a placeholder suffix has to be committable. The names that carry real
    // credentials must not drift into the except along the way.
    const engine = newEngine('strict');
    for (const path of [
        '.env.example',
        '.env.local.example',
        '.env.ci.template',
        'services/api/.env.sample',
        'deploy/.env.staging.dist',
        '.env.defaults',
    ]) {
        assert.equal(engine.checkPaths([path]).length, 0, path);
    }
    for (const path of [
        '.env',
        '.env.local',
        '.env.development',
        '.env.production',
        '.env.test',
        'services/api/.env.production',
    ]) {
        assert.ok(matchFor(engine.checkPaths([path]), 'secret.dotenv'), path);
    }
});

test('public certificates are allowed while private credential content is blocked', () => {
    const engine = newEngine('clean');
    const certificate = [
        '-----BEGIN CERTIFICATE-----',
        'MIIBplaceholderPublicCertificateMaterial',
        '-----END CERTIFICATE-----',
    ].join('\n');
    assert.equal(engine.checkPaths(['certificates/server.pem']).length, 0);
    assert.equal(engine.checkContent('certificates/server.pem', certificate).length, 0);

    const privateKey = `${BEGIN}PRIVATE KEY-----\nMIIEplaceholder`;
    assert.ok(matchFor(
        engine.checkContent('certificates/server.pem', privateKey),
        'secret.private-key-content'
    ));
    for (const privateHeader of [
        `${BEGIN}ENCRYPTED PRIVATE KEY-----`,
        `${BEGIN}PGP PRIVATE KEY BLOCK-----`,
    ]) {
        assert.ok(matchFor(
            engine.checkContent('certificates/private.pem', `${privateHeader}\nplaceholder`),
            'secret.private-key-content'
        ));
    }

    const serviceAccount = `"private_key": "${BEGIN}PRIVATE KEY-----\\nMIIEplaceholder"`;
    assert.ok(matchFor(
        engine.checkContent('config/service-account.json', serviceAccount),
        'secret.service-account-key'
    ));
});

// The file holds an OAuth access token. Filed as ephemeral-state it rides the
// hygiene path, which clean and compliance treat as advisory; as a secret it
// reaches the backstop that stops a commit when the guard is bypassed.
test('.claude/.credentials.json is classified as a secret, not as session state', () => {
    for (const profile of ['clean', 'strict', 'compliance']) {
        const engine = newEngine(profile);
        const findings = engine.checkPaths(['.claude/.credentials.json']);
        assert.ok(findings.length > 0, `${profile}: credentials file not flagged at all`);
        assert.equal(
            findings[0].category,
            'secret',
            `${profile}: an OAuth token file must carry the secret category`
        );
        assert.equal(findings[0].decision, 'block', `${profile}: credentials file must block`);
    }
});

// Keys are assembled at runtime for the same reason the private-key fixtures
// are: a literal key in this source would trip the rule it tests and break the
// self-hosting guard below.
test('secret.provider-token covers the LLM and SaaS key prefixes', () => {
    const engine = newEngine('clean');
    const keys = [
        ['Anthropic', `sk-ant-api03-${'a'.repeat(95)}`],
        ['OpenAI project', `sk-proj-${'a'.repeat(48)}`],
        ['Google', `AIza${'a'.repeat(35)}`],
        ['Stripe live secret', `sk_live_${'a'.repeat(24)}`],
        ['Stripe restricted', `rk_live_${'a'.repeat(24)}`],
        ['HuggingFace', `hf_${'a'.repeat(34)}`],
        ['SendGrid', `SG.${'a'.repeat(22)}.${'b'.repeat(43)}`],
    ];
    for (const [label, key] of keys) {
        const findings = engine.checkContent('src/llm.py', `API_KEY = "${key}"`);
        assert.ok(matchFor(findings, 'secret.provider-token'), `${label} key reached the index undetected`);
    }
});

test('provider key placeholders and environment references stay clean', () => {
    const engine = newEngine('clean');
    const benign = [
        'ANTHROPIC_API_KEY = "sk-ant-api03-REPLACE_ME"',
        'GOOGLE_API_KEY = "AIzaSyExample"',
        'STRIPE_KEY = "sk_live_placeholder"',
        'HF_TOKEN = "hf_your_token_here"',
        'key = os.environ["ANTHROPIC_API_KEY"]',
        'ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}',
        'client = Anthropic(api_key=settings.anthropic_api_key)',
    ];
    for (const line of benign) {
        const findings = engine.checkContent('src/llm.py', line);
        assert.equal(
            matchFor(findings, 'secret.provider-token'),
            undefined,
            `false positive on a placeholder that a real repo would hold: ${line}`
        );
    }
});

test("aimhooman's own rule pack and secret fixtures do not trip the secret rule", () => {
    // Self-hosting guard: the shipped rule pack contains secret patterns and
    // the tests embed private-key fixtures. These source files must not trip
    // the secret rule, or CI range scans of this repository block on
    // themselves. Fixtures build the header at runtime and the rule pack's PGP
    // form is merged into the generic private-key pattern so neither self-matches.
    const engine = newEngine('strict');
    const files = [
        'rules/secrets.json',
        'tests/rule-contracts.test.mjs',
        'tests/cli.test.mjs',
    ];
    for (const relative of files) {
        const content = readFileSync(join(ROOT, relative), 'utf8');
        const secretFindings = engine.checkContent(relative, content)
            .filter((finding) => finding.category === 'secret');
        assert.equal(secretFindings.length, 0, `${relative} trips the secret rule: ${
            JSON.stringify(secretFindings.map((finding) => finding.ruleId))
        }`);
    }
});
