import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRules } from '../src/rules.mjs';
import { newEngine } from '../src/scan.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
// Private-key fixtures are assembled at runtime with the BEGIN marker kept in a
// separate fragment so this test source does not itself trip the secret rule.
const BEGIN = '-----BEGIN ';

const contracts = {
    'attribution.claude-coauthor': {
        positive: { text: 'Co-authored-by: Claude Code <noreply@anthropic.com>' },
        nearMiss: { text: 'Co-authored-by: Claude Dupont <claude@example.com>' },
    },
    'attribution.copilot-coauthor': {
        positive: { text: 'Co-authored-by: GitHub Copilot <175728472+Copilot@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Copilot Team <copilot-team@example.com>' },
    },
    'attribution.codex-coauthor': {
        positive: { text: 'Co-authored-by: OpenAI Codex <noreply@openai.com>' },
        nearMiss: { text: 'Co-authored-by: Cody Dexter <cody@openai.com>' },
    },
    'attribution.bot-coauthor': {
        positive: { text: 'Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Robin Ott <robin@example.com>' },
    },
    'attribution.generated-with': {
        positive: { text: 'Generated with Claude Code' },
        nearMiss: { text: 'Do not show the Generated with Claude Code badge in settings.' },
    },
    'attribution.ai-noreply': {
        positive: { text: 'Reviewed-by: Assistant <noreply@openai.com>' },
        nearMiss: { text: 'Report abuse to noreply@openai.com if you see it.' },
    },
    'marker.corner-cut': {
        positive: { path: 'src/parser.js', text: '// ponytail: skip malformed records for now' },
        nearMiss: { path: 'docs/parser.js', text: '// ponytail: example of a prohibited marker' },
    },
    'marker.ai-authored': {
        positive: { path: 'src/parser.js', text: '// generated by AI' },
        nearMiss: { path: 'tests/parser.js', text: '// generated by AI' },
    },
    'claude.local-settings': {
        positive: { path: 'packages/web/.claude/settings.local.json' },
        nearMiss: { path: 'packages/web/.claude/settings.json' },
    },
    'claude.session-state': {
        positive: { path: '.claude/session-2026-07-13.json' },
        nearMiss: { path: '.claude/commands/release.md' },
    },
    'codex.session-state': {
        positive: { path: '.codex/sessions/2026/rollout.jsonl' },
        nearMiss: { path: '.codex/config.toml' },
    },
    'copilot.session-state': {
        positive: { path: 'packages/web/.copilot/config.json' },
        nearMiss: { path: 'packages/web/copilot/config.json' },
    },
    'cursor.session-state': {
        positive: { path: '.cursor/chats/feature.json' },
        nearMiss: { path: '.cursor/rules/project.mdc' },
    },
    'aider.history': {
        positive: { path: 'packages/web/.aider.conf.yml' },
        nearMiss: { path: 'packages/web/aider.conf.yml' },
    },
    'specstory.history': {
        positive: { path: '.specstory/history/session.json' },
        nearMiss: { path: 'docs/specstory/history.md' },
    },
    'continue.sessions': {
        positive: { path: '.continue/sessions/active.json' },
        nearMiss: { path: '.continue/config.yaml' },
    },
    'secret.dotenv': {
        positive: { path: 'services/api/.env.production' },
        nearMiss: { path: 'services/api/.env.example' },
    },
    'secret.private-key': {
        positive: { path: 'certificates/id_ed25519' },
        nearMiss: { path: 'certificates/server.pem' },
    },
    'secret.aws-credentials': {
        positive: { path: 'deploy/.aws/credentials' },
        nearMiss: { path: 'deploy/.aws/config' },
    },
    'generic.agent-instructions': {
        positive: { path: 'packages/api/AGENTS.md' },
        nearMiss: { path: 'docs/agent-guide.md' },
    },
    'generic.project-policy': {
        positive: { path: '.aimhooman.json' },
        nearMiss: { path: '.aimhooman.example.json' },
    },
    'playwright-mcp.state': {
        positive: { path: '.playwright-mcp/traces/run.json' },
        nearMiss: { path: 'playwright.config.mjs' },
    },
    'remember.state': {
        positive: { path: 'packages/app/.remember/notes.json' },
        nearMiss: { path: 'docs/REMEMBER.md' },
    },
    'superpowers.state': {
        positive: { path: '.superpowers/cache/state.json' },
        nearMiss: { path: '.superpowers.md' },
    },
    'agent.state': {
        positive: { path: '.agent/state.json' },
        nearMiss: { path: '.agents/rules/aimhooman.md' },
    },
    'secret.private-key-content': {
        positive: { path: 'config/credential.txt', text: `${BEGIN}OPENSSH PRIVATE KEY-----` },
        nearMiss: { path: 'certificates/server.pem', text: '-----BEGIN CERTIFICATE-----' },
    },
    'secret.service-account-key': {
        positive: { path: 'config/service-account.json', text: `  "private_key": "${BEGIN}PRIVATE KEY-----\\nMII..."` },
        nearMiss: { path: 'config/service-account.example.json', text: '  "private_key": "${SERVICE_ACCOUNT_PRIVATE_KEY}"' },
    },
    'secret.aws-key-content': {
        positive: { path: 'config/aws.ini', text: `aws_secret_access_key = ${'a'.repeat(40)}` },
        nearMiss: { path: 'config/aws.example.ini', text: 'aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}' },
    },
    'secret.provider-token': {
        positive: { path: 'config/token.txt', text: `ghp_${'a'.repeat(36)}` },
        nearMiss: { path: 'config/token.example.txt', text: 'ghp_REPLACE_ME' },
    },
};

function findingsFor(engine, rule, input) {
    if (rule.kind === 'path') return engine.checkPaths([input.path]);
    if (rule.kind === 'message') return engine.checkMessage(input.text);
    return engine.checkContent(input.path, input.text);
}

function matchFor(findings, ruleId) {
    return findings
        .flatMap((finding) => finding.matchedRules)
        .find((match) => match.ruleId === ruleId);
}

test('every built-in rule has a positive and a meaningful near-miss contract', () => {
    const rules = loadRules();
    const ruleIds = rules.map((rule) => rule.id).sort();
    assert.deepEqual(
        Object.keys(contracts).sort(),
        ruleIds,
        'update the contract registry whenever the built-in rule catalog changes'
    );

    const engine = newEngine('clean');
    for (const rule of rules) {
        const contract = contracts[rule.id];
        assert.ok(contract.positive, `${rule.id} needs a positive contract`);
        assert.ok(contract.nearMiss, `${rule.id} needs a near-miss contract`);

        const positive = matchFor(findingsFor(engine, rule, contract.positive), rule.id);
        assert.ok(positive, `${rule.id} did not match its positive contract`);
        assert.equal(positive.decision, rule.actions.clean, `${rule.id} clean decision changed`);

        const nearMiss = matchFor(findingsFor(engine, rule, contract.nearMiss), rule.id);
        assert.equal(nearMiss, undefined, `${rule.id} matched its near-miss contract`);
    }
});

test('source markers stay out of documentation, tests, dependencies, and generated output', () => {
    const engine = newEngine('strict');
    const excludedPaths = [
        'docs/example.js',
        'test/example.js',
        'tests/example.js',
        'fixtures/example.js',
        '__fixtures__/example.js',
        'vendor/example.js',
        'third_party/example.js',
        'node_modules/example/index.js',
        'dist/example.js',
        'build/example.js',
        'coverage/example.js',
        'generated/example.js',
        'src/example.generated.js',
        'src/example.min.js',
        'src/example.map',
        'src/example.md',
    ];
    const markerIds = new Set(['marker.corner-cut', 'marker.ai-authored']);
    for (const path of excludedPaths) {
        const findings = engine.checkContent(path, '// ponytail: shortcut\n// generated by AI');
        const ids = findings.flatMap((finding) => finding.matchedRuleIds);
        assert.equal(ids.some((id) => markerIds.has(id)), false, path);
    }

    assert.ok(matchFor(engine.checkContent('src/example.js', '// ponytail: shortcut'), 'marker.corner-cut'));
    assert.ok(matchFor(engine.checkContent('src/example.js', '// generated by AI'), 'marker.ai-authored'));
});

test('corner-cut labels match case-insensitively without broadening near misses', () => {
    for (const profile of ['clean', 'strict', 'compliance']) {
        const engine = newEngine(profile);
        const expected = profile === 'strict' ? 'block' : 'review';
        for (const label of ['ponytail', 'Ponytail', 'PONYTAIL', 'Caveman', 'YAGNI-ONELINER']) {
            const match = matchFor(
                engine.checkContent('src/example.js', `// ${label}: shortcut`),
                'marker.corner-cut',
            );
            assert.equal(match?.decision, expected, `${profile}: ${label}`);
        }
        assert.equal(
            matchFor(engine.checkContent('src/example.js', '// ponytail : is prose'), 'marker.corner-cut'),
            undefined,
        );
    }
});

test('security paths opt into case-insensitive matching without changing Git path identity globally', () => {
    const engine = newEngine('strict');
    const cases = [
        ['.ENV', 'secret.dotenv'],
        ['nested/.EnV.Production', 'secret.dotenv'],
        ['deploy/.AWS/CREDENTIALS', 'secret.aws-credentials'],
        ['keys/ID_ED25519', 'secret.private-key'],
    ];
    for (const [path, ruleId] of cases) {
        assert.ok(matchFor(engine.checkPaths([path]), ruleId), path);
    }
    assert.equal(engine.checkPaths(['.ENV.EXAMPLE']).length, 0);
    assert.equal(engine.checkPaths(['.CLAUDE/session.json']).length, 0);
});

test('message attribution repair is exact and compliance preserves disclosures', () => {
    const clean = newEngine('clean');
    const compliance = newEngine('compliance');
    const exactLines = [
        'Co-authored-by: Claude <noreply@anthropic.com>',
        'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
        'Co-authored-by: Codex <noreply@openai.com>',
        'Generated by ChatGPT',
        '🤖 Generated with [Claude Code](https://claude.ai/code)',
    ];
    for (const line of exactLines) {
        const input = `Subject\n\n${line}\nDetail\n`;
        const fixed = clean.fixMessage(input);
        assert.equal(fixed.removed.length, 1, line);
        assert.equal(fixed.cleaned, 'Subject\n\nDetail\n', line);
        assert.equal(compliance.checkMessage(input).length, 0, line);
        assert.equal(compliance.fixMessage(input).cleaned, input, line);
    }

    const nearMisses = [
        'Co-authored-by: Claude Dupont <claude@example.com>',
        'Do not show the Generated by ChatGPT badge in settings.',
        'Report abuse to noreply@openai.com if you see it.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
        assert.deepEqual(clean.fixMessage(line), { cleaned: line, removed: [] }, line);
    }
});

test('attribution rules block the footer Claude Code emits today', () => {
    const clean = newEngine('clean');
    const message = [
        'feat: add thing',
        '',
        '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
        '',
        'Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>',
        '',
    ].join('\n');

    const fixed = clean.fixMessage(message);
    assert.equal(fixed.removed.length, 2, 'both footer lines must be repaired');
    assert.equal(fixed.cleaned.includes('Generated with'), false);
    assert.equal(fixed.cleaned.includes('noreply@anthropic.com'), false);
    assert.ok(fixed.cleaned.startsWith('feat: add thing'), 'the subject must survive');
});

test('attribution patterns never pin a vendor URL', () => {
    // Vendor links are marketing surface and get rebranded (claude.ai/code ->
    // claude.com/claude-code); a pinned one rots silently while CI stays green.
    // Match the link's shape and anchor on the noreply mail domain, which is
    // infrastructure and does not move.
    for (const rule of loadRules().filter((rule) => rule.category === 'ai-attribution')) {
        for (const pattern of rule.match.content ?? []) {
            assert.equal(
                /https?:/i.test(pattern),
                false,
                `${rule.id} pins a vendor URL: ${pattern}`
            );
        }
    }
});

test('attribution patterns stay cheap on adversarial input', () => {
    // A trailer whose "<" never arrives. Built-in patterns are exempt from the
    // local input cap (src/rules.mjs), so an unbounded commit message line
    // reaches them directly; an ambiguous quantifier pair here cost 49s at this
    // length. The budget is loose on purpose: it catches catastrophic
    // backtracking, not slow machines.
    const engine = newEngine('clean');
    const line = `x-by:${' '.repeat(6400)}`;
    const start = process.hrtime.bigint();
    engine.checkMessage(line);
    const ms = Number(process.hrtime.bigint() - start) / 1e6;
    assert.ok(ms < 1000, `attribution scan took ${ms.toFixed(0)}ms on adversarial input`);
});

test('generalized attribution patterns do not swallow ordinary trailers or prose', () => {
    const clean = newEngine('clean');
    const nearMisses = [
        'Generated with [our release script](https://ci.example.com/docs)',
        'Co-authored-by: Claude Dupont <claude.dupont@example.com>',
        'Co-authored-by: Codexter Ltd <team@example.com>',
        'Reviewed-by: Robin Ott <robin@example.com>',
        'See https://claude.com/claude-code for the changelog.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
    }
});

test('public certificates are allowed while private credential content is blocked', () => {
    const engine = newEngine('clean');
    const certificate = [
        '-----BEGIN CERTIFICATE-----',
        'MIIBplaceholderPublicCertificateMaterial',
        '-----END CERTIFICATE-----',
    ].join('\n');
    assert.equal(engine.checkPaths(['certificates/server.pem']).length, 0);
    assert.equal(engine.checkContent('certificates/server.pem', certificate).length, 0);

    const privateKey = `${BEGIN}PRIVATE KEY-----\nMIIEplaceholder`;
    assert.ok(matchFor(
        engine.checkContent('certificates/server.pem', privateKey),
        'secret.private-key-content'
    ));
    for (const privateHeader of [
        `${BEGIN}ENCRYPTED PRIVATE KEY-----`,
        `${BEGIN}PGP PRIVATE KEY BLOCK-----`,
    ]) {
        assert.ok(matchFor(
            engine.checkContent('certificates/private.pem', `${privateHeader}\nplaceholder`),
            'secret.private-key-content'
        ));
    }

    const serviceAccount = `"private_key": "${BEGIN}PRIVATE KEY-----\\nMIIEplaceholder"`;
    assert.ok(matchFor(
        engine.checkContent('config/service-account.json', serviceAccount),
        'secret.service-account-key'
    ));
});

test("aimhooman's own rule pack and secret fixtures do not trip the secret rule", () => {
    // Self-hosting guard: the shipped rule pack contains secret patterns and
    // the tests embed private-key fixtures. These source files must not trip
    // the secret rule, or CI range scans of this repository block on
    // themselves. Fixtures build the header at runtime and the rule pack's PGP
    // form is merged into the generic private-key pattern so neither self-matches.
    const engine = newEngine('strict');
    const files = [
        'rules/secrets.json',
        'tests/rule-contracts.test.mjs',
        'tests/cli.test.mjs',
    ];
    for (const relative of files) {
        const content = readFileSync(join(ROOT, relative), 'utf8');
        const secretFindings = engine.checkContent(relative, content)
            .filter((finding) => finding.category === 'secret');
        assert.equal(secretFindings.length, 0, `${relative} trips the secret rule: ${
            JSON.stringify(secretFindings.map((finding) => finding.ruleId))
        }`);
    }
});
