import test from 'node:test';
import assert from 'node:assert/strict';
import { loadRules } from '../src/rules.mjs';
import { newEngine } from '../src/scan.mjs';

const contracts = {
    'attribution.claude-coauthor': {
        positive: { text: 'Co-authored-by: Claude Code <noreply@anthropic.com>' },
        nearMiss: { text: 'Co-authored-by: Claude Dupont <claude@example.com>' },
    },
    'attribution.copilot-coauthor': {
        positive: { text: 'Co-authored-by: GitHub Copilot <175728472+Copilot@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Copilot Team <copilot-team@example.com>' },
    },
    'attribution.codex-coauthor': {
        positive: { text: 'Co-authored-by: OpenAI Codex <noreply@openai.com>' },
        nearMiss: { text: 'Co-authored-by: Cody Dexter <cody@openai.com>' },
    },
    'attribution.bot-coauthor': {
        positive: { text: 'Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>' },
        nearMiss: { text: 'Co-authored-by: Robin Ott <robin@example.com>' },
    },
    'attribution.generated-with': {
        positive: { text: 'Generated with Claude Code' },
        nearMiss: { text: 'Do not show the Generated with Claude Code badge in settings.' },
    },
    'attribution.ai-noreply': {
        positive: { text: 'Reviewed-by: Assistant <noreply@openai.com>' },
        nearMiss: { text: 'Report abuse to noreply@openai.com if you see it.' },
    },
    'marker.corner-cut': {
        positive: { path: 'src/parser.js', text: '// ponytail: skip malformed records for now' },
        nearMiss: { path: 'docs/parser.js', text: '// ponytail: example of a prohibited marker' },
    },
    'marker.ai-authored': {
        positive: { path: 'src/parser.js', text: '// generated by AI' },
        nearMiss: { path: 'tests/parser.js', text: '// generated by AI' },
    },
    'claude.local-settings': {
        positive: { path: 'packages/web/.claude/settings.local.json' },
        nearMiss: { path: 'packages/web/.claude/settings.json' },
    },
    'claude.session-state': {
        positive: { path: '.claude/session-2026-07-13.json' },
        nearMiss: { path: '.claude/commands/release.md' },
    },
    'codex.session-state': {
        positive: { path: '.codex/sessions/2026/rollout.jsonl' },
        nearMiss: { path: '.codex/config.toml' },
    },
    'copilot.session-state': {
        positive: { path: 'packages/web/.copilot/config.json' },
        nearMiss: { path: 'packages/web/copilot/config.json' },
    },
    'cursor.session-state': {
        positive: { path: '.cursor/chats/feature.json' },
        nearMiss: { path: '.cursor/rules/project.mdc' },
    },
    'aider.history': {
        positive: { path: 'packages/web/.aider.conf.yml' },
        nearMiss: { path: 'packages/web/aider.conf.yml' },
    },
    'specstory.history': {
        positive: { path: '.specstory/history/session.json' },
        nearMiss: { path: 'docs/specstory/history.md' },
    },
    'continue.sessions': {
        positive: { path: '.continue/sessions/active.json' },
        nearMiss: { path: '.continue/config.yaml' },
    },
    'generic.agent-instructions': {
        positive: { path: 'packages/api/AGENTS.md' },
        nearMiss: { path: 'docs/agent-guide.md' },
    },
    'generic.project-policy': {
        positive: { path: '.aimhooman.json' },
        nearMiss: { path: '.aimhooman.example.json' },
    },
    'playwright-mcp.state': {
        positive: { path: '.playwright-mcp/traces/run.json' },
        nearMiss: { path: 'playwright.config.mjs' },
    },
    'remember.state': {
        positive: { path: 'packages/app/.remember/notes.json' },
        nearMiss: { path: 'docs/REMEMBER.md' },
    },
    'superpowers.state': {
        positive: { path: '.superpowers/cache/state.json' },
        nearMiss: { path: '.superpowers.md' },
    },
    'agent.state': {
        positive: { path: '.agent/state.json' },
        nearMiss: { path: '.agents/rules/aimhooman.md' },
    },
};

function findingsFor(engine, rule, input) {
    if (rule.kind === 'path') return engine.checkPaths([input.path]);
    if (rule.kind === 'message') return engine.checkMessage(input.text);
    return engine.checkContent(input.path, input.text);
}

function matchFor(findings, ruleId) {
    return findings
        .flatMap((finding) => finding.matchedRules)
        .find((match) => match.ruleId === ruleId);
}

test('every built-in rule has a positive and a meaningful near-miss contract', () => {
    const rules = loadRules();
    const ruleIds = rules.map((rule) => rule.id).sort();
    assert.deepEqual(
        Object.keys(contracts).sort(),
        ruleIds,
        'update the contract registry whenever the built-in rule catalog changes'
    );

    const engine = newEngine('clean');
    for (const rule of rules) {
        const contract = contracts[rule.id];
        assert.ok(contract.positive, `${rule.id} needs a positive contract`);
        assert.ok(contract.nearMiss, `${rule.id} needs a near-miss contract`);

        const positive = matchFor(findingsFor(engine, rule, contract.positive), rule.id);
        assert.ok(positive, `${rule.id} did not match its positive contract`);
        assert.equal(positive.decision, rule.actions.clean, `${rule.id} clean decision changed`);

        const nearMiss = matchFor(findingsFor(engine, rule, contract.nearMiss), rule.id);
        assert.equal(nearMiss, undefined, `${rule.id} matched its near-miss contract`);
    }
});

test('source markers stay out of documentation, tests, dependencies, and generated output', () => {
    const engine = newEngine('strict');
    const excludedPaths = [
        'docs/example.js',
        'test/example.js',
        'tests/example.js',
        'src/__tests__/example.js',
        'pkg/testdata/golden.js',
        'fixtures/example.js',
        '__fixtures__/example.js',
        'vendor/example.js',
        'vendored/example.js',
        'third_party/example.js',
        'node_modules/example/index.js',
        'dist/example.js',
        'build/example.js',
        'out/example.js',
        'target/example.js',
        '.next/static/example.js',
        'coverage/example.js',
        'generated/example.js',
        'src/example.generated.js',
        'src/example.min.js',
        'src/example.map',
        'src/example.md',
        'src/example.mdx',
        'src/example.markdown',
        'src/example.rst',
        'src/example.test.js',
        'src/example.spec.ts',
        'pkg/example_test.go',
        'spec/models/user_spec.rb',
    ];
    const markerIds = new Set(['marker.corner-cut', 'marker.ai-authored']);
    for (const path of excludedPaths) {
        const findings = engine.checkContent(path, '// ponytail: shortcut\n// generated by AI');
        const ids = findings.flatMap((finding) => finding.matchedRuleIds);
        assert.equal(ids.some((id) => markerIds.has(id)), false, path);
    }

    assert.ok(matchFor(engine.checkContent('src/example.js', '// ponytail: shortcut'), 'marker.corner-cut'));
    assert.ok(matchFor(engine.checkContent('src/example.js', '// generated by AI'), 'marker.ai-authored'));
    // Build output is excepted at the repository root only. `out` and `spec` are
    // ordinary module names, and a marker in one is owned source.
    assert.ok(matchFor(engine.checkContent('src/out/json.js', '// ponytail: shortcut'), 'marker.corner-cut'));
    assert.ok(matchFor(engine.checkContent('src/spec/openapi-builder.js', '// ponytail: shortcut'), 'marker.corner-cut'));
});

test('marker.ai-authored matches the marker phrase, not a product that ships an AI feature', () => {
    // "AI-generated" is vocabulary, not a marker: it is a UI label, a column
    // name, a union member and a disclaimer in any product with an AI feature.
    const engine = newEngine('strict');
    const ownedSource = [
        ['src/ui/Badge.tsx', '<Badge>AI-generated</Badge>'],
        ['src/db/schema.ts', '  aiGenerated: boolean("ai_generated").notNull(),'],
        ['src/api/types.ts', 'type Source = "human" | "ai-generated";'],
        ['src/copy/strings.ts', '"disclaimer": "AI-generated content may be inaccurate"'],
    ];
    for (const [path, line] of ownedSource) {
        assert.equal(matchFor(engine.checkContent(path, line), 'marker.ai-authored'), undefined, line);
    }
    for (const vendor of ['AI', 'Copilot', 'Claude', 'ChatGPT', 'Codex']) {
        assert.ok(
            matchFor(engine.checkContent('src/parser.js', `// generated by ${vendor}`), 'marker.ai-authored'),
            vendor,
        );
    }
});

test('corner-cut labels match case-insensitively without broadening near misses', () => {
    for (const profile of ['clean', 'strict', 'compliance']) {
        const engine = newEngine(profile);
        const expected = profile === 'strict' ? 'block' : 'review';
        for (const label of ['ponytail', 'Ponytail', 'PONYTAIL', 'Caveman', 'YAGNI-ONELINER']) {
            const match = matchFor(
                engine.checkContent('src/example.js', `// ${label}: shortcut`),
                'marker.corner-cut',
            );
            assert.equal(match?.decision, expected, `${profile}: ${label}`);
        }
        assert.equal(
            matchFor(engine.checkContent('src/example.js', '// ponytail : is prose'), 'marker.corner-cut'),
            undefined,
        );
    }
});

test('session and policy paths match case-insensitively; instruction paths do not', () => {
    const engine = newEngine('strict');
    // On APFS and NTFS these are the same file as their lowercase spellings, and
    // Git records the case the caller typed rather than the case on disk.
    const cases = [
        ['.CLAUDE/session.json', 'claude.session-state'],
        ['.Claude/settings.local.json', 'claude.local-settings'],
        ['.Codex/sessions/rollout.jsonl', 'codex.session-state'],
        ['.Cursor/chats/feature.json', 'cursor.session-state'],
        ['.Aimhooman.json', 'generic.project-policy'],
    ];
    for (const [path, ruleId] of cases) {
        assert.ok(matchFor(engine.checkPaths([path]), ruleId), path);
    }

    // The negative control for the opt-in: generic.agent-instructions stays
    // case-sensitive, so folding case is still a per-rule decision rather than a
    // global one. Its names lowercase to ordinary documentation filenames, which
    // must keep committing freely.
    for (const path of ['docs/claude.md', 'docs/gemini.md', 'website/content/blog/agents.md']) {
        assert.equal(engine.checkPaths([path]).length, 0, path);
    }
});

test('the review-required rules print the bound review command as their fix', () => {
    // A bare `allow` writes no head and no object binding, so it exempts every
    // future content of the path. Only `review` binds to the reviewed object, so
    // it is the only remediation these two can honestly print.
    const reviewRequired = new Set(['generic.agent-instructions', 'generic.project-policy']);
    const rules = loadRules().filter((rule) => reviewRequired.has(rule.id));
    assert.equal(rules.length, reviewRequired.size, 'the review-required rule set moved');
    for (const rule of rules) {
        const fix = rule.remediation.join('\n');
        assert.match(fix, /aimhooman review .* --head <commit>/, `${rule.id} must name the bound command`);
        assert.equal(/aimhooman allow\b/.test(fix), false, `${rule.id} prints an unbound allow as its fix`);
    }
});

test('message attribution repair is exact and compliance preserves disclosures', () => {
    const clean = newEngine('clean');
    const compliance = newEngine('compliance');
    const exactLines = [
        'Co-authored-by: Claude <noreply@anthropic.com>',
        'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
        'Co-authored-by: Codex <noreply@openai.com>',
        'Generated by ChatGPT',
        '🤖 Generated with [Claude Code](https://claude.ai/code)',
    ];
    for (const line of exactLines) {
        const input = `Subject\n\n${line}\nDetail\n`;
        const fixed = clean.fixMessage(input);
        assert.equal(fixed.removed.length, 1, line);
        assert.equal(fixed.cleaned, 'Subject\n\nDetail\n', line);
        assert.equal(compliance.checkMessage(input).length, 0, line);
        assert.equal(compliance.fixMessage(input).cleaned, input, line);
    }

    const nearMisses = [
        'Co-authored-by: Claude Dupont <claude@example.com>',
        'Do not show the Generated by ChatGPT badge in settings.',
        'Report abuse to noreply@openai.com if you see it.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
        assert.deepEqual(clean.fixMessage(line), { cleaned: line, removed: [] }, line);
    }
});

test('attribution rules block the footer Claude Code emits today', () => {
    const clean = newEngine('clean');
    const message = [
        'feat: add thing',
        '',
        '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
        '',
        'Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com>',
        '',
    ].join('\n');

    const fixed = clean.fixMessage(message);
    assert.equal(fixed.removed.length, 2, 'both footer lines must be repaired');
    assert.equal(fixed.cleaned.includes('Generated with'), false);
    assert.equal(fixed.cleaned.includes('noreply@anthropic.com'), false);
    assert.ok(fixed.cleaned.startsWith('feat: add thing'), 'the subject must survive');
});

test('attribution patterns pin neither a vendor URL nor a product display name', () => {
    // Vendor links are marketing surface and get rebranded (claude.ai/code ->
    // claude.com/claude-code); a pinned one rots silently while CI stays green.
    // Match the link's shape and anchor on the noreply mail domain, which is
    // infrastructure and does not move. Product names rot the same way — the
    // footer already grew from "Claude Code" to "Claude Sonnet 4.5" — so pin the
    // vendor and let the suffix follow it.
    for (const rule of loadRules().filter((rule) => rule.category === 'ai-attribution')) {
        for (const pattern of rule.match.content ?? []) {
            assert.equal(
                /https?:/i.test(pattern),
                false,
                `${rule.id} pins a vendor URL: ${pattern}`
            );
            assert.equal(
                /\b(?:code|sonnet|opus|haiku)\b/i.test(pattern),
                false,
                `${rule.id} pins a product display name: ${pattern}`
            );
        }
    }
});

test('the generated-with rule survives a model suffix, a version and an emoji', () => {
    const clean = newEngine('clean');
    const footers = [
        'Generated with Claude Code',
        '🤖 Generated with Claude Code',
        'Generated with Claude Code 🤖',
        'Generated with Claude Sonnet 4.5',
        'Generated with Claude Opus 4.8',
        'Generated with Claude Code v2.0.1',
        '🤖 Generated with [Claude Sonnet 4.5](https://claude.com/claude-code)',
        // The gpt-N forms live only inside the alternation; nothing else covers
        // them, so dropping them would otherwise go unnoticed.
        'Generated by GPT-4',
        'Generated by GPT-4.5',
        'Generated by GPT-5',
        'Generated by ChatGPT',
        'Generated with GitHub Copilot',
        'Generated with OpenAI Codex',
        'Generated with Cursor',
    ];
    for (const line of footers) {
        const match = matchFor(clean.checkMessage(line), 'attribution.generated-with');
        assert.equal(match?.decision, 'block', line);
    }
});

test('attribution patterns stay cheap on adversarial input', () => {
    // A trailer whose "<" never arrives. Built-in patterns are exempt from the
    // local input cap (src/rules.mjs), so an unbounded commit message line
    // reaches them directly; an ambiguous quantifier pair here cost 49s at this
    // length. The budget is loose on purpose: it catches catastrophic
    // backtracking, not slow machines.
    const engine = newEngine('clean');
    const line = `x-by:${' '.repeat(6400)}`;
    const start = process.hrtime.bigint();
    engine.checkMessage(line);
    const ms = Number(process.hrtime.bigint() - start) / 1e6;
    assert.ok(ms < 1000, `attribution scan took ${ms.toFixed(0)}ms on adversarial input`);
});

test('generalized attribution patterns do not swallow ordinary trailers or prose', () => {
    const clean = newEngine('clean');
    const nearMisses = [
        'Generated with [our release script](https://ci.example.com/docs)',
        'Co-authored-by: Claude Dupont <claude.dupont@example.com>',
        'Co-authored-by: Codexter Ltd <team@example.com>',
        'Reviewed-by: Robin Ott <robin@example.com>',
        'See https://claude.com/claude-code for the changelog.',
    ];
    for (const line of nearMisses) {
        assert.equal(clean.checkMessage(line).length, 0, line);
    }
});
