import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openRepo, trackedEntries } from '../src/gitx.mjs';
import { newEngine } from '../src/scan.mjs';
import { scanEntries } from '../src/scan-session.mjs';
import { commitChanges } from '../src/history-scan.mjs';

function fixture() {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-'));
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
    writeFileSync(join(dir, 'one.txt'), 'generated by AI\n');
    writeFileSync(join(dir, 'two.txt'), 'generated by AI\n');
    execFileSync('git', ['add', '.'], { cwd: dir });
    return dir;
}

test('content scan reads duplicate objects once and reports every path', () => {
    const dir = fixture();
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.complete, true);
        assert.equal(result.stats.objects_read, 1);
        assert.equal(result.stats.files_scanned, 2);
        assert.deepEqual(result.findings.map((finding) => finding.path).sort(), ['one.txt', 'two.txt']);
        assert.equal(result.findings.every((finding) => finding.objectId), true);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('content scan makes size and total budgets visible', () => {
    const dir = fixture();
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 4,
            maxTotalBytes: 4,
        });
        assert.equal(result.complete, false);
        assert.equal(result.stats.skipped['size-limit'], 2);
        assert.equal(result.stats.files_scanned, 0);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('binary blobs consume the cumulative byte budget', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-binary-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        writeFileSync(join(dir, 'one.bin'), Buffer.from([0, 1, 2, 3, 4, 5]));
        writeFileSync(join(dir, 'two.bin'), Buffer.from([0, 6, 7, 8, 9, 10]));
        execFileSync('git', ['add', '.'], { cwd: dir });

        const repo = openRepo(dir);
        const complete = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 10,
            maxTotalBytes: 12,
        });
        assert.equal(complete.complete, true);
        assert.equal(complete.stats.bytes_scanned, 12);
        assert.equal(complete.stats.skipped.binary, 2);

        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 10,
            maxTotalBytes: 6,
        });
        assert.equal(result.complete, false);
        assert.equal(result.stats.bytes_scanned, 6);
        assert.equal(result.stats.files_scanned, 0);
        assert.equal(result.stats.skipped.binary, 1);
        assert.equal(result.stats.skipped['total-byte-limit'], 1);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('binary blobs skip whole: no content rule reads them and the scan stays complete', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-utf16-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        // NUL-bearing bytes with no byte-order mark stay binary. Nothing here
        // says whether they are text, and guessing costs more than it buys: a
        // misread image decoded into garbage would hand the content rules
        // nonsense, and a block finding on clean unstages the user's asset.
        writeFileSync(join(dir, 'deploy-notes.txt'), Buffer.from('// generated by AI\n', 'utf16le'));
        execFileSync('git', ['add', '.'], { cwd: dir });

        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.complete, true);
        assert.equal(result.stats.skipped.binary, 1);
        assert.equal(result.stats.files_scanned, 0);
        assert.equal(result.findings.length, 0);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

// A byte-order mark says the bytes are UTF-16 text, so the NUL padding is not
// evidence of a binary file. PowerShell 5.1 writes exactly this from `>`,
// `Out-File` and `Tee-Object`, which is how a Windows developer ends up with an
// AI-marker file that no content rule ever reads.
function repositoryWithBlob(name, bytes) {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-bom-'));
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
    writeFileSync(join(dir, name), bytes);
    execFileSync('git', ['add', '.'], { cwd: dir });
    return dir;
}

test('UTF-16 text with a byte-order mark is read by the content rules', () => {
    const body = Buffer.from('// generated by AI\n', 'utf16le');
    const dir = repositoryWithBlob('deploy-notes.txt', Buffer.concat([Buffer.from([0xff, 0xfe]), body]));
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.stats.files_scanned, 1, 'a BOM-marked UTF-16 blob must be scanned, not skipped');
        assert.ok(
            result.findings.some((f) => f.matchedRuleIds.includes('marker.ai-authored')),
            'the marker in UTF-16LE text must produce the same finding it does in UTF-8',
        );
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('big-endian UTF-16 text with a byte-order mark is read by the content rules', () => {
    const body = Buffer.from('// generated by AI\n', 'utf16le').swap16();
    const dir = repositoryWithBlob('deploy-notes.txt', Buffer.concat([Buffer.from([0xfe, 0xff]), body]));
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.ok(
            result.findings.some((f) => f.matchedRuleIds.includes('marker.ai-authored')),
            'the marker in UTF-16BE text must produce the same finding it does in UTF-8',
        );
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('an odd-length blob claiming a byte-order mark is left to the binary skip', () => {
    // swap16() throws on odd lengths; the pre-commit hook must not crash on a
    // truncated file, so an impossible UTF-16 length falls through to binary.
    const dir = repositoryWithBlob('truncated.bin', Buffer.from([0xfe, 0xff, 0x00, 0x2f, 0x00]));
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.stats.skipped.binary, 1);
        assert.equal(result.complete, true);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('git stderr from a passing blob read is captured, not printed', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-stderr-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        writeFileSync(join(dir, 'one.txt'), 'generated by AI\n');
        execFileSync('git', ['add', '.'], { cwd: dir });
        // A --reference clone whose reference was deleted leaves a stale
        // alternates file. Git then writes `error:` to stderr and still exits 0,
        // so only the wrapper's stdio decides whether the user reads it.
        writeFileSync(join(dir, '.git/objects/info/alternates'), `${join(dir, 'gone', 'objects')}\n`);

        const repo = openRepo(dir);
        const entries = trackedEntries(repo);
        const leaked = [];
        const write = process.stderr.write;
        process.stderr.write = (chunk) => (leaked.push(String(chunk)), true);
        try {
            assert.equal(scanEntries(repo, newEngine('strict'), entries).findings.length, 1);
        } finally {
            process.stderr.write = write;
        }
        assert.equal(leaked.join(''), '');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

// 12d-F1: scanEntries used to read the full blob, so a file that contained a
// flagged line ELSEWHERE (an AI-authored marker in a fixture string on line 10)
// blocked a commit that only edited line 1. With hunk-narrowing (W4), only the
// changed line ranges reach checkContent, so an unrelated edit no longer trips
// a marker that lives outside the diff. Entries here come from commitChanges,
// which carries the parent commit needed to compute the changed hunks.
function repositoryWithBase(file, content) {
    const dir = mkdtempSync(join(tmpdir(), 'aim-hunk-'));
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
    writeFileSync(join(dir, file), content);
    execFileSync('git', ['add', file], { cwd: dir });
    execFileSync('git', ['commit', '-q', '-m', 'base'], { cwd: dir });
    return dir;
}

function headAndParent(dir) {
    const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: dir, encoding: 'utf8' }).trim();
    const parent = execFileSync('git', ['rev-parse', 'HEAD~'], { cwd: dir, encoding: 'utf8' }).trim();
    return { head, parent };
}

test('hunk-narrowing: an unrelated edit does not trip a marker elsewhere in the file', () => {
    // Base file: an AI-authored marker on line 6 (left inside a fixture
    // string). The second commit edits line 1 only (an unrelated comment).
    // The marker is NOT in the changed hunk, so it must not produce a finding.
    const lines = [
        '// top of file',
        'package main',
        '',
        'func Fixture() string {',
        '  return `',
        '// generated by AI',
        '`',
        '}',
    ];
    const dir = repositoryWithBase('main.go', `${lines.join('\n')}\n`);
    try {
        // Edit line 1 only (the unrelated comment).
        writeFileSync(join(dir, 'main.go'), '// edited top of file\n' + lines.slice(1).join('\n') + '\n');
        execFileSync('git', ['add', 'main.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'edit comment'], { cwd: dir });

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const markers = result.findings.filter((f) => f.matchedRuleIds.includes('marker.ai-authored'));
        assert.equal(markers.length, 0, 'an unrelated edit must not trip a marker outside the changed hunk');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('hunk-narrowing: a marker inside the changed hunk still blocks (guardrail)', () => {
    // Base file: a benign comment. The second commit ADDS a marker line. That
    // line IS in the changed hunk, so it must still produce a finding. This is
    // the regression guard against over-narrowing: the fix must not open a
    // hole for a marker added in the diff.
    const dir = repositoryWithBase('main.go', '// benign base\npackage main\n');
    try {
        writeFileSync(join(dir, 'main.go'), '// benign base\npackage main\n// generated by AI\n');
        execFileSync('git', ['add', 'main.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'add marker'], { cwd: dir });

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const markers = result.findings.filter((f) => f.matchedRuleIds.includes('marker.ai-authored'));
        assert.ok(markers.length >= 1, 'a marker inside the changed hunk must still block');
        // The finding must be anchored to the actual added marker line, not line 1.
        assert.equal(markers.every((f) => f.line >= 3), true, 'marker finding must anchor to the added line');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

// Regression guard for the batched collectLineRanges (one diff per commit, not
// one per file). A commit that touches MULTIPLE files must narrow each file to
// its own changed hunks independently: a marker added in file A must block,
// while an unrelated edit in file B (whose OWN content is clean) must not trip
// a marker that lives in file B elsewhere. If the batched path-attribution
// were wrong (e.g. hunks attributed to the wrong file), this would catch it.
test('hunk-narrowing: batched multi-file diff attributes each file its own hunks', () => {
    // File A: a clean base. Commit adds a marker (must block).
    // File B: base contains a marker on line 6 (in a fixture string). Commit
    // edits line 1 only (must NOT block — the marker is outside B's hunk).
    const baseB = [
        '// top of file B',
        'package main',
        '',
        'func Fixture() string {',
        '  return `',
        '// generated by AI',
        '`',
        '}',
    ].join('\n') + '\n';
    const dir = mkdtempSync(join(tmpdir(), 'aim-hunk-batch-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        // Base commit: A is benign, B has the marker.
        writeFileSync(join(dir, 'a.go'), '// benign A\npackage main\n');
        writeFileSync(join(dir, 'b.go'), baseB);
        execFileSync('git', ['add', 'a.go', 'b.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'base'], { cwd: dir });

        // Second commit: A gets a marker added (block); B's line 1 edited (no block).
        writeFileSync(join(dir, 'a.go'), '// benign A\npackage main\n// generated by AI\n');
        writeFileSync(join(dir, 'b.go'), '// edited top of file B\n' + baseB.split('\n').slice(1).join('\n') + '\n');
        execFileSync('git', ['add', 'a.go', 'b.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'edit both'], { cwd: dir });

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const markers = result.findings.filter((f) => f.matchedRuleIds.includes('marker.ai-authored'));
        // Exactly one marker finding: from a.go (where the marker was added), not
        // b.go (where the marker lives outside the edited hunk). If batching
        // mis-attributed b.go's hunks to a.go or vice versa, this count or the
        // path would be wrong.
        const markerPaths = [...new Set(markers.map((f) => f.path))];
        assert.ok(markers.length >= 1, 'the marker added to a.go must block');
        assert.deepEqual(markerPaths, ['a.go'], 'only a.go (the file whose hunk added the marker) should report; b.go must not');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

// A unified diff renders an added line as `+` followed by its content, so a
// source line starting `++ ` arrives as `+++ ...` — the same shape as a new-file
// header. Hunk bodies must be consumed by the line budget the `@@` header
// declares, never re-read as headers, or everything after the forged line in
// that file is attributed to a path nobody scans.
const FORGERY_BASE = [
    '// top of file',
    'int i = 0;',
    '',
    'func Fixture() {',
    '  step()',
    '  step()',
    '  step()',
    '  // benign line',
    '  step()',
    '}',
].join('\n') + '\n';

function commitForgedHeader(dir, secondLine) {
    const lines = FORGERY_BASE.split('\n');
    lines[1] = secondLine;
    lines[7] = '// generated by AI';
    writeFileSync(join(dir, 'main.go'), lines.join('\n'));
    execFileSync('git', ['add', 'main.go'], { cwd: dir });
    execFileSync('git', ['commit', '-q', '-m', 'edit'], { cwd: dir });
}

test('a hunk body that reads like a file header does not hide the rest of the file', () => {
    // Line 2 becomes `++ i;`, which git renders as `+++ i;`. Line 8 becomes a
    // marker in a later hunk. The marker must still be scanned.
    const dir = repositoryWithBase('main.go', FORGERY_BASE);
    try {
        commitForgedHeader(dir, '++ i;');

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const markers = result.findings.filter((f) => f.matchedRuleIds.includes('marker.ai-authored'));
        assert.ok(markers.length >= 1, 'a line rendering as `+++ path` must not blind the hunks after it');
        assert.deepEqual([...new Set(markers.map((f) => f.path))], ['main.go']);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('a hunk body reading like a deleted-file header does not hide the rest of the file', () => {
    // `++ /dev/null` renders as `+++ /dev/null`, which the header branch treats
    // as a deletion and would drop every remaining hunk in the file.
    const dir = repositoryWithBase('main.go', FORGERY_BASE);
    try {
        commitForgedHeader(dir, '++ /dev/null');

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const markers = result.findings.filter((f) => f.matchedRuleIds.includes('marker.ai-authored'));
        assert.ok(markers.length >= 1, 'a line rendering as `+++ /dev/null` must not blind the hunks after it');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});
