import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openRepo, trackedEntries } from '../src/gitx.mjs';
import { newEngine } from '../src/scan.mjs';
import { scanEntries } from '../src/scan-session.mjs';
import { commitChanges } from '../src/history-scan.mjs';

function fixture() {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-'));
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
    writeFileSync(join(dir, 'one.txt'), 'generated by AI\n');
    writeFileSync(join(dir, 'two.txt'), 'generated by AI\n');
    execFileSync('git', ['add', '.'], { cwd: dir });
    return dir;
}

test('content scan reads duplicate objects once and reports every path', () => {
    const dir = fixture();
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.complete, true);
        assert.equal(result.stats.objects_read, 1);
        assert.equal(result.stats.files_scanned, 2);
        assert.deepEqual(result.findings.map((finding) => finding.path).sort(), ['one.txt', 'two.txt']);
        assert.equal(result.findings.every((finding) => finding.objectId), true);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('content scan makes size and total budgets visible', () => {
    const dir = fixture();
    try {
        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 4,
            maxTotalBytes: 4,
        });
        assert.equal(result.complete, false);
        assert.equal(result.stats.skipped['size-limit'], 2);
        assert.equal(result.stats.files_scanned, 0);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('binary blobs consume the cumulative byte budget', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-binary-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        writeFileSync(join(dir, 'one.bin'), Buffer.from([0, 1, 2, 3, 4, 5]));
        writeFileSync(join(dir, 'two.bin'), Buffer.from([0, 6, 7, 8, 9, 10]));
        execFileSync('git', ['add', '.'], { cwd: dir });

        const repo = openRepo(dir);
        const complete = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 10,
            maxTotalBytes: 12,
        });
        assert.equal(complete.complete, true);
        assert.equal(complete.stats.bytes_scanned, 12);
        assert.equal(complete.stats.skipped.binary, 2);

        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo), {
            maxFileBytes: 10,
            maxTotalBytes: 6,
        });
        assert.equal(result.complete, false);
        assert.equal(result.stats.bytes_scanned, 6);
        assert.equal(result.stats.files_scanned, 0);
        assert.equal(result.stats.skipped.binary, 1);
        assert.equal(result.stats.skipped['total-byte-limit'], 1);
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('a UTF-16 key cannot hide its signature behind the encoding NULs', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-utf16-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        // PowerShell 5.1 still writes UTF-16LE from `>`, `Out-File` and
        // `Tee-Object`, so redirecting key material into an ordinary filename
        // lands here without anyone trying to evade the rules. One NUL per
        // character, not one NUL, is what a latin1 view has to survive.
        const key = '-----BE' + 'GIN OPENSSH PRIVATE KEY-----\nmaterial\n';
        writeFileSync(join(dir, 'deploy-notes.txt'), Buffer.from(key, 'utf16le'));
        execFileSync('git', ['add', '.'], { cwd: dir });

        const repo = openRepo(dir);
        const result = scanEntries(repo, newEngine('strict'), trackedEntries(repo));
        assert.equal(result.complete, true);
        assert.equal(result.stats.skipped.binary, 1);
        assert.equal(result.stats.files_scanned, 0);
        assert.equal(result.findings.length, 1);
        assert.ok(result.findings[0].matchedRuleIds.includes('secret.private-key-content'));
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('git stderr from a passing blob read is captured, not printed', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-stderr-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        writeFileSync(join(dir, 'one.txt'), 'generated by AI\n');
        execFileSync('git', ['add', '.'], { cwd: dir });
        // A --reference clone whose reference was deleted leaves a stale
        // alternates file. Git then writes `error:` to stderr and still exits 0,
        // so only the wrapper's stdio decides whether the user reads it.
        writeFileSync(join(dir, '.git/objects/info/alternates'), `${join(dir, 'gone', 'objects')}\n`);

        const repo = openRepo(dir);
        const entries = trackedEntries(repo);
        const leaked = [];
        const write = process.stderr.write;
        process.stderr.write = (chunk) => (leaked.push(String(chunk)), true);
        try {
            assert.equal(scanEntries(repo, newEngine('strict'), entries).findings.length, 1);
        } finally {
            process.stderr.write = write;
        }
        assert.equal(leaked.join(''), '');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('NUL-classified blobs still run every secret signature in every profile', () => {
    const dir = mkdtempSync(join(tmpdir(), 'aim-session-binary-secret-'));
    try {
        execFileSync('git', ['init', '-q'], { cwd: dir });
        execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
        execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
        const privateHeader = '-----BE' + 'GIN PRIVATE KEY-----';
        const serviceAccount = `{"private_key":"${privateHeader}\\nmaterial"}`;
        const awsCredential = `aws_secret_access_key = ${'a'.repeat(40)}`;
        const providerToken = `ghp_${'a'.repeat(36)}`;
        const fixtures = [
            ['ordinary-0.dat', Buffer.concat([Buffer.from([0]), Buffer.from(privateHeader)])],
            ['ordinary-1.dat', Buffer.concat([Buffer.from('x'.repeat(4000)), Buffer.from([0]), Buffer.from(privateHeader)])],
            ['ordinary-2.dat', Buffer.concat([Buffer.from('x'.repeat(7999)), Buffer.from([0]), Buffer.from(privateHeader)])],
            ['ordinary-3.dat', Buffer.concat([Buffer.from([0]), Buffer.from(serviceAccount)])],
            ['ordinary-4.dat', Buffer.concat([Buffer.from([0]), Buffer.from(awsCredential)])],
            ['ordinary-5.dat', Buffer.concat([Buffer.from([0]), Buffer.from(providerToken)])],
            ['.ENV', Buffer.concat([Buffer.from([0]), Buffer.from(providerToken)])],
        ];
        fixtures.forEach(([path, content]) => writeFileSync(join(dir, path), content));
        execFileSync('git', ['add', '-f', '.'], { cwd: dir });

        const repo = openRepo(dir);
        for (const profile of ['clean', 'strict', 'compliance']) {
            const result = scanEntries(repo, newEngine(profile), trackedEntries(repo));
            assert.equal(result.complete, true, profile);
            assert.equal(result.stats.skipped.binary, fixtures.length, profile);
            assert.equal(result.stats.files_scanned, 0, profile);
            assert.equal(result.findings.length, fixtures.length, profile);
            assert.equal(result.findings.filter((finding) => (
                finding.matchedRuleIds.includes('secret.private-key-content')
            )).length, 4, profile);
            assert.equal(result.findings.some((finding) => (
                finding.matchedRuleIds.includes('secret.service-account-key')
            )), true, profile);
            assert.equal(result.findings.some((finding) => (
                finding.matchedRuleIds.includes('secret.aws-key-content')
            )), true, profile);
            assert.equal(result.findings.some((finding) => (
                finding.matchedRuleIds.includes('secret.provider-token')
            )), true, profile);
        }
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

// 12d-F1: scanEntries used to read the full blob, so a file that contained a
// secret-bearing line ELSEWHERE (a PEM header inside a test string on line 10)
// blocked a commit that only edited line 1. With hunk-narrowing (W4), only the
// changed line ranges reach checkContent, so an unrelated edit no longer trips
// a header that lives outside the diff. Entries here come from commitChanges,
// which carries the parent commit needed to compute the changed hunks.
function repositoryWithBase(file, content) {
    const dir = mkdtempSync(join(tmpdir(), 'aim-hunk-'));
    execFileSync('git', ['init', '-q'], { cwd: dir });
    execFileSync('git', ['config', 'user.name', 'Test'], { cwd: dir });
    execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: dir });
    writeFileSync(join(dir, file), content);
    execFileSync('git', ['add', file], { cwd: dir });
    execFileSync('git', ['commit', '-q', '-m', 'base'], { cwd: dir });
    return dir;
}

function headAndParent(dir) {
    const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: dir, encoding: 'utf8' }).trim();
    const parent = execFileSync('git', ['rev-parse', 'HEAD~'], { cwd: dir, encoding: 'utf8' }).trim();
    return { head, parent };
}

test('hunk-narrowing: an unrelated edit does not trip a PEM header elsewhere in the file', () => {
    // Base file: a PEM private-key header on line 8 (inside a test fixture).
    // The second commit edits line 1 only (an unrelated comment). The PEM
    // header is NOT in the changed hunk, so it must not produce a finding.
    // PEM markers are built from parts so this test file never carries a
    // literal that trips secret.private-key-content on itself.
    const begin = '-----BEGIN ' + 'RSA PRIVATE KEY' + '-----';
    const end = '-----END ' + 'RSA PRIVATE KEY' + '-----';
    const lines = [
        '// top of file',
        'package main',
        '',
        'func TestKey(t *testing.T) {',
        '  const fixture = `',
        begin,
        'MIIEowIBAAKCAQEA0Z3VS5JJcds3xfn',
        end,
        '`',
        '}',
    ];
    const dir = repositoryWithBase('keypair_test.go', `${lines.join('\n')}\n`);
    try {
        // Edit line 1 only (the unrelated comment).
        writeFileSync(join(dir, 'keypair_test.go'), '// edited top of file\n' + lines.slice(1).join('\n') + '\n');
        execFileSync('git', ['add', 'keypair_test.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'edit comment'], { cwd: dir });

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const pem = result.findings.filter((f) => f.matchedRuleIds.includes('secret.private-key-content'));
        assert.equal(pem.length, 0, 'an unrelated edit must not trip a PEM header outside the changed hunk');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});

test('hunk-narrowing: a PEM header inside the changed hunk still blocks (guardrail)', () => {
    // Base file: a benign comment. The second commit ADDS a line with a PEM
    // private-key header. That header IS in the changed hunk, so it must still
    // produce a finding. This is the regression guard against over-narrowing:
    // the fix must not open a hole for a secret added in the diff.
    // PEM markers built from parts (see the test above) so this file does not
    // trip secret.private-key-content on itself.
    const begin = '-----BEGIN ' + 'RSA PRIVATE KEY' + '-----';
    const end = '-----END ' + 'RSA PRIVATE KEY' + '-----';
    const dir = repositoryWithBase('keypair.go', '// benign base\npackage main\n');
    try {
        writeFileSync(join(dir, 'keypair.go'), `// benign base\npackage main\n${begin}\nMIIEowIBAAKCAQEA0Z3VS5JJcds3xfn\n${end}\n`);
        execFileSync('git', ['add', 'keypair.go'], { cwd: dir });
        execFileSync('git', ['commit', '-q', '-m', 'add key'], { cwd: dir });

        const repo = openRepo(dir);
        const { head, parent } = headAndParent(dir);
        const changes = commitChanges(repo, head, head, [parent]);
        const result = scanEntries(repo, newEngine('strict'), changes.entries);
        const pem = result.findings.filter((f) => f.matchedRuleIds.includes('secret.private-key-content'));
        assert.ok(pem.length >= 1, 'a PEM header inside the changed hunk must still block');
        // The finding must be anchored to the actual added header line, not line 1.
        assert.equal(pem.every((f) => f.line >= 3), true, 'PEM finding must anchor to the added header line');
    } finally {
        rmSync(dir, { recursive: true, force: true });
    }
});
